setwd("c://users/lena_/lenium-repo/Explore/")
fileURL = "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
#download.file(fileURL,destfile = "./data.zip")
header<-unlist(read.table(unzip("data.zip","household_power_consumption.txt"), nrows = 1, sep = ";", na.strings = "?"))
data<-read.table(unzip("data.zip","household_power_consumption.txt"), skip = 66636, nrows = 2880, header = TRUE, sep = ";", na.strings = "?", col.names = header)
data$Date = as.Date(data$Date,"%e/%m/%Y")
data$DateTime = paste(data$Date,data$Time)
data$Time=strptime(data$DateTime,format = "%Y-%m-%d %H:%M:%S")
par(mfrow=c(2,2))
with(data,plot(Time,Global_active_power, type="l", main = "", xlab="", ylab = "Global Active Power (kilowatts)"))
with(data,plot(Time,Voltage, type="l", main = "", xlab="datetime", ylab = "Voltage", col="black"))
with(data,plot(Time,Sub_metering_1, type="l", main = "", xlab="", ylab = "Energy Sub Metering", col="black"))
with(data,lines(Time,Sub_metering_2, col="red"))
with(data,lines(Time,Sub_metering_3, col="blue"))
legend("topright",pch="_", col = c("black","red","blue"),legend = names(data)[7:9])
with(data,plot(Time,Global_reactive_power, type="l", main = "", xlab="datetime", ylab = "Global Reactive Power", col="black"))
dev.copy(png, file = "plot4.png",width=480,height=480)
dev.off()